// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrkklnawbmgvbmklmkou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ya2tsbmF3Ym1ndmJta2xta291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4ODk1NzgsImV4cCI6MjA3NTQ2NTU3OH0.bqijrUUhxNx0yo0JdsQa5u2tcYdV-NgI2WBDTTpJkTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});